import spacy
from spacy.training import Example

train_data = [
    ("Paciente KCFM, 38 anos, primigesta, procedente do interior do estado, admitida nesta maternidade na 37a. semana de gestação com relato de mal-estar associado à dor epigástrica e alteração visual.", {"entities": [(15, 22, "IDADE"), (138, 147, "SINTOMA"), (160, 175, "SINTOMA"), (178, 194, "SINTOMA")]}),
    ("Não havia relato de hipertensão prévia ou no acompanhamento pré-natal.", {"entities": [(20, 31, "SINTOMA"), (60, 69, "PROCEDIMENTO")]}),
    ("O acompanhante relatava o aparecimento de manchas vermelhas escurecidas em todo o corpo e flutuação do nível de consciência nas duas últimas semanas.", {"entities": [(42, 71, "SINTOMA"), (90, 123, "SINTOMA")]}),
    ("O exame físico evidenciava paciente pálida, em bom estado nutricional. Estava lúcida e orientada; pressão arterial (PA) - 180 X110mmHg; freqüência respiratória - 24inc/min e freqüência cardíaca -107bpm.", {"entities": [(2, 13, "PROCEDIMENTO"), (27, 42, "SINTOMA"), (78, 84, "SINTOMA"), (87, 96, "SINTOMA"), (98, 134, "SINTOMA"), (136, 171, "SINTOMA"), (174, 201, "SINTOMA")]}),
    ("Não apresentava sinais de desconforto respiratório e a ausculta pulmonar e cardíaca eram normais. Ao exame do abdome palpava-se o fundo uterino a 10 cm da cicatriz umbilical, batimentos cardíacos fetais (BCF) inaudíveis a ausculta fetal. As extremidades eram bem perfundidas e sem edema.", {"entities": [(26, 50, "SINTOMA"), (55, 83, "PROCEDIMENTO"), (101, 116, "PROCEDIMENTO"), (222, 236, "PROCEDIMENTO"), (281, 286, "SINTOMA")]}),
    ("Apresentava petéquias em face anterior do tórax e interna dos braços.", {"entities": [(12, 21, "SINTOMA")]}),
    ("O exame neurológico mostrou paciente lúcida e orientada sem sinais neurológicos focais ou alterações de reflexos de tronco e osteotendinosos pesquisados e com força muscular normal.", {"entities": [(2, 19, "PROCEDIMENTO"), (37, 43, "SINTOMA"), (60, 86, "SINTOMA"), (90, 122, "SINTOMA")]}),
    ("Eletrocardiograma (ECG) era normal a radiografia de tórax evidenciava discreta cardiomegalia. A ultrassonografia obstétrica com fluxometria à Doppler constatou o óbito fetal.", {"entities": [(0, 23, "PROCEDIMENTO"), (37, 57, "PROCEDIMENTO"), (79, 92, "SINTOMA"), (96, 149, "PROCEDIMENTO"), (162, 173, "DIAGNOSTICO")]}),
    ("Sexo feminino, 73 anos, leucodérmica, com antecedentes pessoais conhecidos de hipertensão arterial, diabetes mellitus tipo 2 insulinotratada, dislipidemia e doença cerebrovascular. Doente negou alergias medicamentosas conhecidas.", {"entities": [(15, 22, "IDADE"), (24, 36, "DOENCA"), (78, 98, "DOENCA"), (100, 124, "DOENCA"), (125, 140, "MEDICAMENTO"), (142, 154, "DOENCA"), (157, 179, "DOENCA")]}),
    ("Recorreu ao serviço de urgência por tosse produtiva com expectoração purulenta e febre (38,1ºC) com 5 dias de evolução.", {"entities": [(36, 41, "SINTOMA"), (56, 78, "SINTOMA"), (81, 86, "SINTOMA")]}),
    ("Analiticamente com aumento dos parâmetros inflamatórios e, radiologicamente, com condensação do lobo inferior esquerdo, a favorecer o diagnóstico de pneumonia adquirida na comunidade.", {"entities": [(19, 55, "SINTOMA"), (81, 118, "SINTOMA"), (149, 158, "DOENCA")]}),
    ("Foi-lhe prescrita amoxicilina/ácido clavulânico, sendo a primeira administração por via endovenosa, no serviço de urgência.", {"entities": [(18, 29, "MEDICAMENTO"), (30, 47, "MEDICAMENTO"), (84, 98, "PROCEDIMENTO")]}),
    ("Aproximadamente 1 minuto após ingestão do fármaco, apresentou rash cutâneo generalizado e alteração do estado de consciência, com saturação periférica de oxigênio, em ar ambiente, de 67%; pressão arterial 87×50mmHg; e frequência cardíaca de 110bpm.", {"entities": [(42, 49, "MEDICAMENTO"), (62, 87, "REACAO"), (90, 124, "REACAO"), (130, 186, "SINTOMA"), (188, 214, "SINTOMA"), (218, 247, "SINTOMA")]}),
    ("Foi medicada com clemastina 2mg e hidrocortisona 200mg, com evolução desfavorável para parada cardiorrespiratória, com posterior recuperação de pulso após Suporte Avançado de Vida, necessidade de entubação orotraqueal e ventilação mecânica invasiva.", {"entities": [(17, 31, "MEDICAMENTO"), (34, 54, "MEDICAMENTO"), (87, 113, "REACAO"), (155, 179, "PROCEDIMENTO"), (196, 217, "PROCEDIMENTO"), (220, 248, "PROCEDIMENTO")]}),
    ("Eletrocardiograma com evidência de supradesnivelamento do segmento ST no território inferior (Figura 1).", {"entities": [(0, 17, "PROCEDIMENTO"), (35, 92, "SINTOMA")]}),
    ("Realizou coronariografia urgente, que revelou doença aterosclerótica difusa, com ausência de lesões obstrutivas (Figura 2).", {"entities": [(9, 24, "PROCEDIMENTO"), (46, 75, "DOENCA"), (93, 111, "SINTOMA")]}),
    ("Verificou-se ainda, na sala de hemodinâmica, a resolução espontânea do supradesnivelamento do segmento ST-T.", {"entities": [(31, 43, "PROCEDIMENTO"), (71, 107, "SINTOMA")]}),
    ("Analiticamente, apresentava-se com pico de troponina I 2,046μg/L, creatinoquinase (CK) total 647U/L e CK-MB 55U/L.", {"entities": [(35, 64, "SINTOMA"), (66, 99, "SINTOMA"), (102, 113, "SINTOMA")]}),
    ("Após contato, a família mencionou alergia prévia à penicilina, que a doente desconhecia.", {"entities": [(51, 61, "MEDICAMENTO")]}),
    ("Doseamento da triptase nas primeiras 6 horas após o choque: 132ng/mL (fortemente positivo).", {"entities": [(14, 22, "MEDICAMENTO")]}),
    ("Foi admitida provável síndrome de Kounis tipo 2 em contexto de toma de amoxicilina/ácido clavulânico.", {"entities": [(22, 47, "DOENCA"), (71, 82, "MEDICAMENTO"), (83, 100, "MEDICAMENTO")]}),
    ("Doente permaneceu 29 horas sob ventilação mecânica, com boa evolução clínica posterior.", {"entities": [(31, 50, "PROCEDIMENTO")]}),
    ("Teve alta com indicação para evitar antibióticos betalactâmicos e foi referenciada à consulta de imunoalergologia.", {"entities": [(36, 64, "MEDICAMENTO"), (97, 113, "ESPECIALIDADE")]}),
    ("Paciente L. M. A., 81 anos, sexo feminino, 1,49 de altura, analfabeta, natural de Alegre (ES), anêmica, hipertensa e diabética não insulino-dependente.", {"entities": [(95, 102, "DOENCA"), (104, 114, "DOENCA"), (117, 126, "DOENCA"), (131, 150, "MEDICAMENTO")]}),
    ("Fazia uso dos seguintes medicamentos: Furosemida 10mg (1 comprimido de 12 em 12 horas) e Propanolol 40mg (1 comprimido de 12 em 12 horas) para tratamento e controle da hipertensão e Glibenclamida 5 mg (1 comprimido de 12 em 12 horas) e Cloridrato de Metformina 850mg (1 comprimido de 12 em 12 horas) para tratamento e controle da Diabetes tipo 2.", {"entities": [(38, 53, "MEDICAMENTO"), (89, 104, "MEDICAMENTO"), (168, 179, "DOENCA"), (182, 200, "MEDICAMENTO"), (236, 265, "MEDICAMENTO"), (330, 345, "DOENCA")]}),
    ("A paciente deu entrada no Pronto-Atendimento do município de Alegre/ES apresentando dispnéia, taquicardia, edemas na face e membros inferiores e sinais de cansaço.", {"entities": [(84, 92, "SINTOMA"), (94, 105, "SINTOMA"), (107, 113, "SINTOMA")]}),
    ("Foi realizada a aferição de pressão arterial que foi de 130 x 90mmHg e apresentou glicemia capilar (HGT) acima do que o aparelho consegue ler, o que mostrou que a paciente estava com níveis muito elevados de glicose no sangue. Houve então a necessidade de aplicar insulina 15 UI na paciente. Após a reestabilização dos níveis de glicose no sangue, a paciente foi encaminhada para o Hospital de Caridade São José no mesmo município onde ficou internada por oito dias.", {"entities": [(16, 44, "PROCEDIMENTO"), (82, 104, "SINTOMA"), (264, 278, "MEDICAMENTO")]}),
    ("Através do exame clinico, foi diagnosticada intoxicação medicamentosa. Ao ser questionada com relação aos medicamentos administrados diariamente e os respectivos horários de administração, a paciente não soube relatar, pois é analfabeta e sua neta era quem preparava os medicamentos para serem administrados por ela. A paciente disse ainda, que por desentendimentos familiares foi necessário trocar a responsável pelo preparo da sua medicação.", {"entities": [(44, 69, "REACAO")]}),
    ("O médico entrou em contato com a responsável e descobriu que a paciente estava fazendo uso, já a duas semanas, de 4 comprimidos de Glibenclamida 5 mg por dia, sendo 2 comprimidos pela manhã e 2 comprimidos a noite.", {"entities": [(114, 149, "MEDICAMENTO")]}),
    ("O excesso de medicamento propiciou a resistência da paciente ao efeito hipoglicemiante do mesmo e, além disso, foi constatado uma interação medicamentosa entre a Glibenclamida 5 mg e a Furosemida 40 mg que promoveu a intoxicação.", {"entities": [(64, 86, "REACAO"), (162, 180, "MEDICAMENTO"), (185, 201, "MEDICAMENTO"), (217, 228, "REACAO")]}),
    ("O médico fez a reavaliação do esquema terapêutico dos medicamentos administrados pela paciente e substituiu a Furosemida 40 mg pelo Hidroclorotiazida e suspendeu a Glibenclamida 5 mg, deixando apenas o Cloridrato de Metformina 850 mg sendo que o horário permaneceu inalterado para todos os medicamentos.", {"entities": [(110, 126, "MEDICAMENTO"), (132, 149, "MEDICAMENTO"), (164, 182, "MEDICAMENTO"), (202, 233, "MEDICAMENTO")]}),
    ("Inicialmente, foram coletados os medicamentos em uso pela paciente, sendo estes representados pelos seguintes medicamentos: Trileptal (Oxarbazepina 300 mg.);Núcleo CMP Gross (Citidina 5-monofosfato dissódico + Uridina 5 trifosfato trissódica + acetato de hidroxicobalamina);", {"entities": [(124, 133, "MEDICAMENTO"), (135, 154, "MEDICAMENTO"), (157, 173, "MEDICAMENTO"), (175, 207, "MEDICAMENTO"), (210, 241, "MEDICAMENTO"), (244, 272, "MEDICAMENTO")]}),
    ("Citoneurin (Vitamina B1 100 mg + Vit B6 100 mg + VitB12 5000 mcg); Fluimucil (Acetilcisteína); Foraseq (Fumarato de formoterol diidratado 12 mcg + budesonida 400 mcg); Atrovent (Brometo de ipratrópio 0,25 mg/mL);", {"entities": [(0, 10, "MEDICAMENTO"), (12, 30, "MEDICAMENTO"), (33, 46, "MEDICAMENTO"), (49, 64, "MEDICAMENTO"), (67, 76, "MEDICAMENTO"), (78, 92, "MEDICAMENTO"), (95, 102, "MEDICAMENTO"), (104, 144, "MEDICAMENTO"), (147, 165, "MEDICAMENTO"), (168, 176, "MEDICAMENTO"), (178, 210, "MEDICAMENTO")]}),
    ("Digecap Zimático (Bromoprida 5 mg + celulose 30 mg + dimeticona 50 mg + pancreatina 100 mg); Lactulona (Lactulose 667 mg); Prednisona (5mg); Rocaltrol (Calcitriol 0,25 mg); Systen (Estradiol Adesivo); Rivotril (Clonazepam 0,5 mg);Nootropil (Piracetam 800mg); ", {"entities": [(0, 16, "MEDICAMENTO"), (18, 33, "MEDICAMENTO"), (36, 50, "MEDICAMENTO"), (53, 69, "MEDICAMENTO"), (72, 90, "MEDICAMENTO"), (93, 102, "MEDICAMENTO"), (104, 120, "MEDICAMENTO"), (123, 139, "MEDICAMENTO"), (141, 150, "MEDICAMENTO"), (152, 170, "MEDICAMENTO"), (181, 198, "MEDICAMENTO"), (201, 209, "MEDICAMENTO"), (211, 228, "MEDICAMENTO"), (230, 239, "MEDICAMENTO"), (241, 256, "MEDICAMENTO")]}),
    ("e Pharmaton (Palmitato de retinol, ginseng, colecalciferol, acetato de tocoferol, nitrato de tiamina, riboflavina, cloridrato de piridoxina, cianocobalamina, biotina, nicotinamida, ácido ascórbico, cobre, manganês, magnésio, ferro, zinco, fosfato de cálcio dibásico, selênio e lecitina de soja. Visto isso, pode-se afirmar que a paciente utilizava 14 medicamentos e, como existiam associações medicamentosas, totalizou-se a administração de 40 substâncias com finalidades medicamentosas. Deste total, 11 substâncias apresentaram uma ou mais interações, inclusive com o aumento no aparecimento de reações adversas a medicamentos (RAM). Assim, os medicamentos prescritos que apresentam um potencial de ocorrer alguma interação clínica foram demonstrados na tabela).", {"entities": [(2, 11, "MEDICAMENTO"), (13, 33, "MEDICAMENTO"), (35, 42, "MEDICAMENTO"), (44, 58, "MEDICAMENTO"), (60, 80, "MEDICAMENTO"), (82, 100, "MEDICAMENTO"), (102, 113, "MEDICAMENTO"), (115, 139, "MEDICAMENTO"), (141, 156, "MEDICAMENTO"), (158, 165, "MEDICAMENTO"), (167, 179, "MEDICAMENTO"), (181, 196, "MEDICAMENTO"), (232, 237, "MEDICAMENTO"), (239, 265, "MEDICAMENTO"), (267, 274, "MEDICAMENTO"), (277, 293, "MEDICAMENTO")]}),
    ("Foi analisada a prescrição médica de uma paciente asmática de 70 anos, acometida por artrite, nevralgia, com constantes desmaios, constipação e insônia. A análise das possíveis interações medicamentosas presentes e das possíveis intervenções a serem necessárias no tratamento farmacológico foi feita de acordo com a literatura técnica-científica.", {"entities": [(50, 65, "DOENCA"), (85, 92, "DOENCA"), (94, 103, "DOENCA"), (120, 128, "REACAO"), (130, 141, "SINTOMA"), (144, 151, "SINTOMA")]}),
    ("Inicialmente, foram coletados os medicamentos em uso pela paciente, sendo estes representados pelos seguintes medicamentos: Trileptal (Oxarbazepina 300 mg.); Núcleo CMP Gross (Citidina 5-monofosfato dissódico + Uridina 5-trifosfato trissódica + acetato de hidroxicobalamina);", {"entities": [(124, 133, "MEDICAMENTO"), (135, 154, "MEDICAMENTO"), (158, 174, "MEDICAMENTO"), (176, 208, "MEDICAMENTO"), (211, 242, "MEDICAMENTO"), (245, 273, "MEDICAMENTO")]}),
    ("Citoneurin (Vitamina B1 100 mg + Vit B6 100 mg + VitB12 5000 mcg); Fluimucil (Acetilcisteína); Foraseq (Fumarato de formoterol diidratado 12 mcg + budesonida 400 mcg); Atrovent (Brometo de ipratrópio 0,25 mg/mL); Digecap Zimático (Bromoprida 5 mg + celulose 30 mg + dimeticona 50 mg + pancreatina 100 mg); ", {"entities": [(0, 10, "MEDICAMENTO"), (12, 30, "MEDICAMENTO"), (33, 46, "MEDICAMENTO"), (49, 64, "MEDICAMENTO"), (67, 76, "MEDICAMENTO"), (78, 92, "MEDICAMENTO"), (95, 102, "MEDICAMENTO"), (104, 144, "MEDICAMENTO"), (147, 165, "MEDICAMENTO"), (168, 176, "MEDICAMENTO"), (178, 210, "MEDICAMENTO"), (213, 229, "MEDICAMENTO"), (231, 246, "MEDICAMENTO"), (249, 263, "MEDICAMENTO"), (266, 282, "MEDICAMENTO"), (285, 303, "MEDICAMENTO")]}),
    ("Lactulona (Lactulose 667 mg); Prednisona (5mg); Rocaltrol (Calcitriol 0,25 mg); Systen (Estradiol Adesivo); Rivotril (Clonazepam 0,5 mg); Nootropil (Piracetam 800mg); ", {"entities": [(0, 9, "MEDICAMENTO"), (11, 27, "MEDICAMENTO"), (30, 46, "MEDICAMENTO"), (48, 57, "MEDICAMENTO"), (59, 77, "MEDICAMENTO"), (88, 105, "MEDICAMENTO"), (108, 116, "MEDICAMENTO"), (118, 135, "MEDICAMENTO"), (138, 147, "MEDICAMENTO"), (149, 164, "MEDICAMENTO")]}),
    ("e Pharmaton (Palmitato de retinol, ginseng, colecalciferol, acetato de tocoferol, nitrato de tiamina, riboflavina, cloridrato de piridoxina, cianocobalamina, biotina, nicotinamida, ácido ascórbico, cobre, manganês, magnésio, ferro, zinco, fosfato de cálcio dibásico, selênio e lecitina de soja. Visto isso, pode-se afirmar que a paciente utilizava 14 medicamentos e, como existiam associações medicamentosas, totalizou-se a administração de 40 substâncias com finalidades medicamentosas. Deste total, 11 substâncias apresentaram uma ou mais interações, inclusive com o aumento no aparecimento de reações adversas a medicamentos (RAM). Assim, os medicamentos prescritos que apresentam um potencial de ocorrer alguma interação clínica foram demonstrados na tabela 1.).", {"entities": [(2, 11, "MEDICAMENTO"), (13, 33, "MEDICAMENTO"), (35, 42, "MEDICAMENTO"), (44, 58, "MEDICAMENTO"), (60, 80, "MEDICAMENTO"), (82, 100, "MEDICAMENTO"), (102, 113, "MEDICAMENTO"), (115, 139, "MEDICAMENTO"), (141, 156, "MEDICAMENTO"), (158, 165, "MEDICAMENTO"), (167, 179, "MEDICAMENTO"), (181, 196, "MEDICAMENTO"), (239, 265, "MEDICAMENTO"), (267, 274, "MEDICAMENTO"), (277, 293, "MEDICAMENTO")]}),
    ("O Sr. João Paciente toma regularmente ácido acetilsalicílico, sofre já há quatro anos de diabetes senil, recebendo de seu médico uma receita contendo glibenclamida (Daonil) e um laxante contendo Plantaginis ovata e Cassia angustifolia (Agiolax).", {"entities": [(38, 60, "MEDICAMENTO"), (89, 103, "DOENCA"), (150, 163, "MEDICAMENTO"), (165, 171, "MEDICAMENTO"), (178, 185, "MEDICAMENTO"), (195, 212, "MEDICAMENTO"), (215, 234, "MEDICAMENTO"), (237, 244, "MEDICAMENTO")]}),
    ("INTERAÇÃO GLIBENCLAMIDA - AGIOLAX? Teoricamente a absorção de substâncias ativas que são administradas concomitante com laxantes pode ser limitada. Este, porém, não é o caso neste estudo.", {"entities": [(26, 33, "MEDICAMENTO"), (120, 182, "MEDICAMENTO")]}),
    ("RECOMENDAÇÃO: Não é necessária nenhuma recomendação ao paciente, pois esta interação teórica não obriga a uma correção de dose da glibenclamida. O uso prolongado de laxantes deve ser desaconselhado.INTERAÇÃO GLIBENCLAMIDA - ÁCIDO ACETILSALICÍLICO?", {"entities": [(130, 143, "MEDICAMENTO"), (165, 173, "MEDICAMENTO"), (208, 221, "MEDICAMENTO"), (224, 246, "MEDICAMENTO")]}),
    ("Nesta combinação existe o perigo de uma hipoglicemia. A interação ocorre raramente, mas é de significado clínico, já que foram observadas hipoglicemias ameaçadoras da vida dos pacientes. O ácido acetilsalicílico possui em doses elevadas (maior 3g/dia) um efeito hipoglicêmico próprio.", {"entities": [(40, 52, "REACAO"), (189, 211, "MEDICAMENTO"), (262, 275, "REACAO")]}),
    ("Ensaios in vitro mostraram que os salicilatos deslocam a tolbutamida e outras sulfoniluréias que se ligam fortemente às proteínas plasmáticas. Através deste deslocamento da ligação protéica, aumenta a concentração do fármaco livre. Já que somente o fármaco livre, não ligado, é farmacologicamente ativo, resulta do aumento da concentração, uma elevação do efeito da substância, com o perigo de uma hipoglicemia. Para a interação este efeito possui significado paralelo.", {"entities": [(34, 45, "MEDICAMENTO"), (57, 68, "MEDICAMENTO"), (78, 92, "MEDICAMENTO"), (398, 410, "REACAO")]}),
    ("RECOMENDAÇÃO: Com a finalidade de evitar a interação, deve ser reduzida a dose de pelo menos um dos medicamentos. Esta interação, no entanto, é raramente descrita. Na regra basta informar ao paciente, já que os diabéticos face à longa convivência com seu estado patológico e de seu tratamento, reconhecem os primeiros sinais de uma hipoglicemia, que pode ocorrer a qualquer momento por hábitos não conseqüentes (como a manutenção incorreta da dieta) ou por esforço físico exagerado.", {"entities": [(211, 220, "DOENCA"), (332, 344, "REACAO")]}),
    ("Através da combinação de ácido acetilsalicílico com outra sulfoniluréia, a carbutamida, que possui uma ligação protéica menor (cerca de 60%), pode também ocorrer reações hipoglicêmicas. Deste modo é frustada a possibilidade de utilizar estecaminho. Para concentrações menores de ácido acetilsalicílico (0,5g/dia) não é de se esperar esta interação.", {"entities": [(25, 47, "MEDICAMENTO"), (58, 71, "DOENCA"), (75, 86, "MEDICAMENTO"), (170, 184, "REACAO")]})
]

nlp = spacy.blank("pt")
ner = nlp.add_pipe("ner")

for text, annotations in train_data:
    for ent in annotations.get("entities"):
        ner.add_label(ent[2])

optimizer = nlp.begin_training()

for itn in range(100):
    for text, annotations in train_data:
        doc = nlp.make_doc(text)
        example = Example.from_dict(doc, annotations)
        nlp.update([example], sgd=optimizer)

nlp.to_disk("C:\\Users\\aldat\\OneDrive\\Documents\\[TCC] NER\\trained_pipeline")